name: Live 05 CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Linting
        run: npm ci:lint

      - name: Typechecking
        run: npm typecheck

      - name: Tests
        run: npm test:ci
